<a href="https://colab.research.google.com/github/ravidox/hello-world/blob/main/SP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np
from scipy.sparse import  eye, vstack
from scipy.sparse.linalg import  spsolve

class markovChain(object): 
    
    def __init__(self,P=None,direct=False):
        self.P              = P 
        self.pi             = None #steady state probability vector
        self.mapping        = {}   #mapping used to identify states
        self.initialState   = None #a dummy initial state             
        
    @property
    def size(self):
        return len(self.mapping)

    def func(self): 
        size = P.shape[0]
        dP = P - eye(size)
        A = vstack([np.ones(size), dP.T[1:,:]]).tocsr()  
        z = np.zeros((size,))
        z[0] = 1      
        self.pi = spsolve(A, z)

    R = int(input("Number of rows:"))
    C = int(input("Number of columns:"))

    print("Enter TPM ")
    entries = list(map(float, input().split()))
    matrix = np.array(entries).reshape(R, C)
    print(matrix)
    P = matrix
    a = markovChain(P)
    a.func()
    print("The steady state is",a.pi)     
    



Number of rows:3
Number of columns:3
Enter TPM 
0.2 0.1 0.7 0.3 0.6 0.1 0.4 0.4 0.2
[[0.2 0.1 0.7]
 [0.3 0.6 0.1]
 [0.4 0.4 0.2]]
The steady state is [0.30107527 0.38709677 0.31182796]
