<a href="https://colab.research.google.com/github/ravidox/hello-world/blob/main/Stochastic_Process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### ***DTMC PROBLEM STATEMENT***

### **Problem Statement**

a. Take input as the TPM for irreducible markov chain 

b. Find Steady State Behavior by solving equations.

c. Simulate this for multiple runs

d. Find behavior from the simulation perspective 

e. Identification of recurrent / transient states  and classes 




### **Finding the Steady State Distribution: Linear Equations**

Linear algebra method can be used to get the steady state. In this process we solve the linear equation Ax=x, where A is our TPM. The code below first takes input for our TPM and then solves for steady state.

In [27]:
import numpy as np                                          
from scipy.sparse import  eye, vstack
from scipy.sparse.linalg import  spsolve

R = int(input("Number of rows:"))
C = int(input("Number of columns:"))
print("Enter TPM ")
entries = list(map(float, input().split()))
matrix = np.array(entries).reshape(R, C)
print(matrix)

class markovChain(object): 
    
    def __init__(self,P=None,direct=False):
        self.P              = P 
        self.I             = None           

    def fun(self): 
        s = P.shape[0]                
        dP = P - eye(s)
        v = vstack([np.ones(s), dP.T[1:]]).tocsr()  
        z = np.zeros((s))
        z[0] = 1      
        self.I = spsolve(v, z)


P = matrix
m = markovChain(P)
m.fun()
print("Steady state",m.I)


Number of rows:3
Number of columns:3
Enter TPM 
0.2 0.6 0.2 0.5 0.4 0.1 0.2 0.3 0.5
[[0.2 0.6 0.2]
 [0.5 0.4 0.1]
 [0.2 0.3 0.5]]
Steady state [0.33333333 0.44444444 0.22222222]


### **Finding the Steady State Distribution : Matrix Multiplication**
 

Matrix multiplication is another method to calculate Steady state. In this we multiply our TPM with an initial matrix and keeps on multiplying the matrix to get a steady state.

In [28]:
steps = 10**6

A_n = P

i = 0
while i < steps: 
    A_n = np.matmul(A_n, P)
    i = i + 1

print("The sationary probability distribution is: ", A_n[0])

The sationary probability distribution is:  [0.33333333 0.44444444 0.22222222]


### **Defining the States in a Markov Chain**

In [29]:
state = { 0 : "STATE 1",
          1 : "STATE 2", 
          2 : "STATE 3"
        } 
state

{0: 'STATE 1', 1: 'STATE 2', 2: 'STATE 3'}

In [30]:
A =matrix
print(A)

[[0.2 0.6 0.2]
 [0.5 0.4 0.1]
 [0.2 0.3 0.5]]


###**Markov Chain as a Random Walk**
To understand how a Markov process works an example of a Markov Process is shown here - Random Walk. This random walk shows the path of the Markov chain for 12 steps.      

In [31]:
n = 12

start_state = 0
print(state[start_state], "---->", end = " ")
previous_state = start_state 

while n > 1:
    current_state = np.random.choice([0,1,2], p = A[previous_state])
    print(state[current_state], "---->", end = " ")
    current_state = previous_state
    n = n - 1 
print("stop")

STATE 1 ----> STATE 1 ----> STATE 3 ----> STATE 1 ----> STATE 2 ----> STATE 1 ----> STATE 2 ----> STATE 2 ----> STATE 2 ----> STATE 3 ----> STATE 2 ----> STATE 2 ----> stop


### **Simulation : Monte Carlo Method** 

Monte Carlo Simulation is a statistical technique which involves repeated random sampling baseed on some probability distribution to find out empirical probability (relative frequncy approach of probability). hence, we use Monte Carlo simulation here to find out how many times a process is in a particular state based on which the steady state distribution is calculated. 

In [32]:
steps = 10**6
start_state = 2 
pi = np.array([0, 0, 0])
pi[start_state] = 1
previous_state = start_state 

i = 0

while i < steps: 
    current_state = np.random.choice([0,1,2], p = A[previous_state])
    pi[current_state] = pi[current_state] + 1
    previous_state = current_state 
    i = i + 1
    
print("The stationary probability distribution is : ", pi/steps)

The stationary probability distribution is :  [0.333273 0.444349 0.222379]


### **Comparison of steady state**

Here, the steady state distribution calculated by all three methods is displayed. As it is observed, Linear equation and matrix multiplication method gives an exact, accurate answer while Monte carlo simulation provides a approximate solution which is very close to the theoretical answer. 




In [33]:
print("Linear method: ",m.I ,"\n")
print("Matrix Multiplication",A_n[0],"\n")
print("Monte Carlo Simulation",pi/steps,"\n")

Linear method:  [0.33333333 0.44444444 0.22222222] 

Matrix Multiplication [0.33333333 0.44444444 0.22222222] 

Monte Carlo Simulation [0.333273 0.444349 0.222379] 



### **Transient and Recurrent States** 

In [34]:
Z= print("TPM for irreducible markov Chain \n",P,"\n")
print("Number of state : ", state, "\n\n")

TPM for irreducible markov Chain 
 [[0.2 0.6 0.2]
 [0.5 0.4 0.1]
 [0.2 0.3 0.5]] 

Number of state :  {0: 'STATE 1', 1: 'STATE 2', 2: 'STATE 3'} 





As we are aware that an irreducible Markov chain with a finite state space
is always recurrent because with a finite number of state it will move back
to the same state in a long run. 


So, State 1,2,3 are all recurrent.