<a href="https://colab.research.google.com/github/ravidox/hello-world/blob/main/Stochastic_Process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Finding the Steady State Distribution: Linear Equations**

In [ ]:
import numpy as np                                          
from scipy.sparse import  eye, vstack
from scipy.sparse.linalg import  spsolve

R = int(input("Number of rows:"))
C = int(input("Number of columns:"))
print("Enter TPM ")
entries = list(map(float, input().split()))
matrix = np.array(entries).reshape(R, C)
print(matrix)

class markovChain(object): 
    
    def __init__(self,P=None,direct=False):
        self.P              = P 
        self.I             = None           

    def fun(self): 
        s = P.shape[0]                
        dP = P - eye(s)
        v = vstack([np.ones(s), dP.T[1:]]).tocsr()  
        z = np.zeros((s))
        z[0] = 1      
        self.I = spsolve(v, z)


P = matrix
m = markovChain(P)
m.fun()
print("Steady state",m.I)


Number of rows:3
Number of columns:3
Enter TPM 
0.2 0.3 0.5 0.1 0.2 0.7 0.4 0.1 0.5
[[0.2 0.3 0.5]
 [0.1 0.2 0.7]
 [0.4 0.1 0.5]]
Steady state [0.28947368 0.1754386  0.53508772]


### **Finding the Steady State Distribution : Matrix Multiplication**
 

In [ ]:
steps = 10**6

A_n = A

i = 0
while i < steps: 
    A_n = np.matmul(A_n, A)
    i = i + 1

print("The sationary probability distribution is: ", A_n[0])

The sationary probability distribution is:  [0.28947368 0.1754386  0.53508772]


### **Defining the States in a Markov Chain**

In [ ]:
state = { 0 : "STATE 1",
          1 : "STATE 2", 
          2 : "STATE 3"
        } 
state

{0: 'STATE 1', 1: 'STATE 2', 2: 'STATE 3'}

In [ ]:
A =matrix
print(A)

[[0.2 0.3 0.5]
 [0.1 0.2 0.7]
 [0.4 0.1 0.5]]


###**Markov Chain as a Random Walk**

In [ ]:
n = 12

start_state = 0
print(state[start_state], "---->", end = " ")
previous_state = start_state 

while n > 1:
    current_state = np.random.choice([0,1,2], p = A[previous_state])
    print(state[current_state], "---->", end = " ")
    current_state = previous_state
    n = n - 1 
print("stop")

STATE 1 ----> STATE 1 ----> STATE 3 ----> STATE 2 ----> STATE 1 ----> STATE 3 ----> STATE 1 ----> STATE 2 ----> STATE 2 ----> STATE 3 ----> STATE 2 ----> STATE 3 ----> stop


### **Simulation : Monte Carlo Method** 

In [ ]:
steps = 10**6
start_state = 2 
pi = np.array([0, 0, 0])
pi[start_state] = 1
previous_state = start_state 

i = 0

while i < steps: 
    current_state = np.random.choice([0,1,2], p = A[previous_state])
    pi[current_state] = pi[current_state] + 1
    previous_state = current_state 
    i = i + 1
    
print("The stationary probability distribution is : ", pi/steps)

The stationary probability distribution is :  [0.289926 0.174953 0.535122]


### **Comparison of steady state**




In [ ]:
print("Linear method: ",m.I ,"\n")
print("Matrix Multiplication",A_n[0],"\n")
print("Monte Carlo Simulation",pi/steps,"\n")

Linear method:  [0.28947368 0.1754386  0.53508772] 

Matrix Multiplication [0.28947368 0.1754386  0.53508772] 

Monte Carlo Simulation [0.289926 0.174953 0.535122] 

